name: Build, push & scan image

on:
  push:
    branches:
       - actions


jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
                # Require: The version of golangci-lint to use.
                # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
                # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.54
      
                # Optional: working directory, useful for monorepos
                # working-directory: somedir
      
                # Optional: golangci-lint command line arguments.
                #
                # Note: By default, the `.golangci.yml` file should be at the root of the repository.
                # The location of the configuration file can be changed by using `--config=`
          args: --timeout=3m 
                --out-format=checkstyle:golangci-lint.out,colored-line-number
                --issues-exit-code=0 
      
                # Optional: show only new issues if it's a pull request. The default value is `false`.
                # only-new-issues: true
      
                # Optional: if set to true, then all caching functionality will be completely disabled,
                #           takes precedence over all other caching options.
                # skip-cache: true
      
                # Optional: if set to true, then the action won't cache or restore ~/go/pkg.
                # skip-pkg-cache: true
      
                # Optional: if set to true, then the action won't cache or restore ~/.cache/go-build.
                # skip-build-cache: true
      
                # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
                # install-mode: "goinstall"



                # jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: '1.21'

#       - name: Install golangci-lint
#         run: |
#           curl -sSfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
#           golangci-lint --version

#       - name: Run golangci-lint
#         run: |
#           golangci-lint run 
#             --timeout 3m 
#             --out-format=checkstyle:golangci-lint.out,colored-line-number   

#       - name: Print linting results
#         run: cat golangci-lint.out

#       - name: Upload linting results
#         uses: actions/upload-artifact@v2
#         with:
#           name: golangci-lint-results
#           path: golangci-lint.out